server:
  port: 1001
spring:
  application:
    name: eureka_server
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:1001/eureka/
---
#server:
#  port: 1002
#spring:
#  application:
#    name: eureka_server
#eureka:
#  instance:
#    hostname: peer2
#    prefer-ip-address: true
#  client:
##    register-with-eureka: false
##    fetch-registry: false
#    service-url:
#      defaultZone: http://peer2:1002/eureka/
